services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  GeorgRinger\Eventnews\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  GeorgRinger\Eventnews\EventListener\NewsImportListener:
    tags:
      - name: event.listener
        identifier: 'eventnews-newsimportlistener'
        event: GeorgRinger\News\Event\NewsImportPostHydrateEvent

  GeorgRinger\Eventnews\EventListener\AfterFlexFormDataStructureParsedEventListener:
    tags:
      - name: event.listener
        identifier: 'eventnews-flexformhook'
        event: TYPO3\CMS\Core\Configuration\Event\AfterFlexFormDataStructureParsedEvent

  GeorgRinger\Eventnews\EventListener\Administration\ModifyQueryEventListener:
    tags:
      - name: event.listener
        identifier: 'eventnews-administration-modifyquery'
        event: GeorgRinger\NewsAdministration\Event\ModifyQueryEvent

  GeorgRinger\Eventnews\EventListener\Administration\IndexActionEventListener:
    tags:
      - name: event.listener
        identifier: 'eventnews-administration-modifyhtml'
        event: GeorgRinger\NewsAdministration\Event\AdministrationIndexActionEvent

  GeorgRinger\Eventnews\EventListener\ModifyDemandRepositoryEventListener:
    tags:
      - name: event.listener
        identifier: 'eventnews-modifydemandrepository'
        event: GeorgRinger\News\Event\ModifyDemandRepositoryEvent
